"""initial_schema

Revision ID: 75d48eb17ca2
Revises: 
Create Date: 2026-03-16 18:52:58.968126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d48eb17ca2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messenger_import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('raw_content_path', sa.String(length=500), nullable=False),
    sa.Column('group_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('sender_mappings', sa.Text(), nullable=True),
    sa.Column('imported_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('patronymic', sa.String(length=200), nullable=True),
    sa.Column('birth_last_name', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('name_display_order', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date_raw', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('birth_date_precision', sa.String(length=20), nullable=True),
    sa.Column('death_date_raw', sa.String(length=50), nullable=True),
    sa.Column('death_date', sa.String(length=10), nullable=True),
    sa.Column('death_date_precision', sa.String(length=20), nullable=True),
    sa.Column('is_living', sa.Boolean(), nullable=False),
    sa.Column('birth_place', sa.String(length=300), nullable=True),
    sa.Column('birth_country_code', sa.String(length=2), nullable=True),
    sa.Column('residence_place', sa.String(length=300), nullable=True),
    sa.Column('residence_country_code', sa.String(length=2), nullable=True),
    sa.Column('burial_place', sa.String(length=300), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('contact_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('contact_telegram', sa.String(length=100), nullable=True),
    sa.Column('contact_signal', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('photo_url', sa.String(length=2000), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('account_state', sa.String(length=20), nullable=False),
    sa.Column('facebook_id', sa.String(length=100), nullable=True),
    sa.Column('facebook_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('facebook_token_expires', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index('idx_persons_country_code', ['residence_country_code'], unique=False)
        batch_op.create_index('idx_persons_facebook_id', ['facebook_id'], unique=True, sqlite_where=sa.text('facebook_id IS NOT NULL'))
        batch_op.create_index('idx_persons_is_root', ['is_root'], unique=False, sqlite_where=sa.text('is_root = 1'))

    op.create_table('whatsapp_import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('raw_content_path', sa.String(length=500), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=True),
    sa.Column('group_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('sender_mappings', sa.Text(), nullable=True),
    sa.Column('imported_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('required_voters', sa.Text(), nullable=False),
    sa.Column('threshold', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_external_identity')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('embed_url', sa.String(length=2000), nullable=True),
    sa.Column('embed_provider', sa.String(length=50), nullable=True),
    sa.Column('embed_html', sa.Text(), nullable=True),
    sa.Column('caption', sa.String(length=1000), nullable=True),
    sa.Column('taken_date', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_profile', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memorial_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('memorial_photo_id', sa.String(length=36), nullable=True),
    sa.Column('memorial_bio', sa.Text(), nullable=True),
    sa.Column('memorial_message', sa.Text(), nullable=True),
    sa.Column('memorial_music_url', sa.String(length=2000), nullable=True),
    sa.Column('memorial_wishes', sa.String(length=2000), nullable=True),
    sa.Column('contact_visible_after_death', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('moments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_ids', sa.Text(), nullable=True),
    sa.Column('milestone_type', sa.String(length=30), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_precision', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('posted_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('push_channel', sa.String(length=20), nullable=False),
    sa.Column('push_phone', sa.String(length=20), nullable=True),
    sa.Column('push_email', sa.String(length=320), nullable=True),
    sa.Column('push_telegram_id', sa.String(length=100), nullable=True),
    sa.Column('push_frequency', sa.String(length=20), nullable=False),
    sa.Column('push_milestones', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_detail', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('parent_id != child_id', name='ck_no_self_parent'),
    sa.ForeignKeyConstraint(['child_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', 'kind', name='uq_parent_child_kind')
    )
    op.create_table('partnerships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_a_id', sa.String(length=36), nullable=False),
    sa.Column('person_b_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('start_date_precision', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('end_date_precision', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('person_a_id != person_b_id', name='ck_no_self_partnership'),
    sa.CheckConstraint('person_a_id < person_b_id', name='ck_canonical_order'),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', 'kind', 'start_date', name='uq_partnership_pair_kind_date')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_person_id', ['person_id'], unique=False)
        batch_op.create_index('idx_sessions_token_hash', ['token_hash'], unique=False)

    op.create_table('approval_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('voter_id', sa.String(length=36), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'voter_id', name='uq_vote_per_voter')
    )
    op.create_table('moment_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('moment_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moment_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('moment_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moment_id', 'person_id', name='uq_reaction_per_person')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_deliveries')
    op.drop_table('moment_reactions')
    op.drop_table('moment_comments')
    op.drop_table('approval_votes')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_token_hash')
        batch_op.drop_index('idx_sessions_person_id')

    op.drop_table('user_sessions')
    op.drop_table('partnerships')
    op.drop_table('parent_child')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_table('moments')
    op.drop_table('memorial_plans')
    op.drop_table('media')
    op.drop_table('magic_link_tokens')
    op.drop_table('invites')
    op.drop_table('external_identities')
    op.drop_table('approval_requests')
    op.drop_table('agent_api_keys')
    op.drop_table('whatsapp_import_batches')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('idx_persons_is_root', sqlite_where=sa.text('is_root = 1'))
        batch_op.drop_index('idx_persons_facebook_id', sqlite_where=sa.text('facebook_id IS NOT NULL'))
        batch_op.drop_index('idx_persons_country_code')

    op.drop_table('persons')
    op.drop_table('messenger_import_batches')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
